id: P005468
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:52:10.216719
source_metadata:
  id: bdr:W10308
  title: ལམ་འབྲས་ཁོག་ཕུབ
  author: ''
  volumes:
    de75e9d8bbf7427a84a3ab184a3e7164:
      image_group_id: I6122
      title: ''
      volume_number: 1
      total_pages: 604
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
