id: P005468
initial_creation_type: ocr
source_metadata:
  id: bdr:W10308
  title: ལམ་འབྲས་ཁོག་ཕུབ
  author: ''
  volumes:
    de75e9d8bbf7427a84a3ab184a3e7164:
      image_group_id: I6122
      title: ''
      volume_number: 1
      total_pages: 604
      base_file: v001.txt
