id: I8845A842
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T03:16:50+00:00'
last_modified: '2022-06-08T03:17:55.067938+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W10308
  title: ལམ་འབྲས་ཁོག་ཕུབ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CC19:
      image_group_id: I6122
      title: ''
      total_pages: 604
      order: 1
      base_file: CC19.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
